# Generated by Django 3.0.6 on 2020-05-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blog',
        ),
    ]
