# Generated by Django 3.0.6 on 2020-06-03 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('body', models.TextField(null=True)),
                ('meeting_time', models.DurationField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('writer', models.CharField(max_length=500, null=True)),
                ('like', models.ManyToManyField(blank=True, related_name='User_apply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
