# Generated by Django 3.0.6 on 2020-05-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('body', models.TextField(null=True)),
                ('meeting_time', models.DurationField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
