# Generated by Django 3.0.6 on 2020-05-31 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_board_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='User_apply', to=settings.AUTH_USER_MODEL),
        ),
    ]
